// ═══════════════════════════════════
// DATA — все данные приложения
// ═══════════════════════════════════

// ══════════════════════════════════════════
// DATA
// ══════════════════════════════════════════

const SPECIALIZATIONS = [
  { id:'it',    icon:'💻', name:'IT / Системный администратор', desc:'Сети, серверы, Active Directory, Linux, DevOps' },
  { id:'med',   icon:'🏥', name:'Медицина / Здравоохранение',   desc:'Клиническая терминология, анамнез, диагнозы' },
  { id:'law',   icon:'⚖️', name:'Юриспруденция / Право',        desc:'Договоры, судопроизводство, законодательство' },
  { id:'fin',   icon:'💰', name:'Финансы / Банковское дело',    desc:'Бухгалтерия, инвестиции, банковские операции' },
  { id:'eng',   icon:'⚙️', name:'Инженерия / Производство',     desc:'Технические чертежи, оборудование, стандарты' },
  { id:'biz',   icon:'📊', name:'Бизнес / Менеджмент',          desc:'Переговоры, презентации, деловая переписка' },
];

const LEVEL_TEST = [
  {q:"Hallo",opts:["Пока","Привет","Спасибо","Да"],a:1,lvl:'A1'},
  {q:"danke",opts:["пожалуйста","нет","спасибо","да"],a:2,lvl:'A1'},
  {q:"das Haus",opts:["машина","дом","стол","дерево"],a:1,lvl:'A1'},
  {q:"ich arbeite",opts:["я учусь","я иду","я работаю","я сплю"],a:2,lvl:'A1'},
  {q:"der Bahnhof",opts:["аэропорт","вокзал","больница","рынок"],a:1,lvl:'A2'},
  {q:"Wie spät ist es?",opts:["Сколько стоит?","Который час?","Как далеко?","Что это?"],a:1,lvl:'A2'},
  {q:"Ich würde gern...",opts:["Я должен...","Я не могу...","Я хотел бы...","Мне нравится..."],a:2,lvl:'B1'},
  {q:"obwohl",opts:["потому что","хотя","если","когда"],a:1,lvl:'B1'},
  {q:"das Gleichgewicht",opts:["возможность","равновесие","противоречие","исследование"],a:1,lvl:'B2'},
  {q:"ungeachtet",opts:["несмотря на","согласно","вместо","благодаря"],a:0,lvl:'B2'},
];

const vocabularyData = [
  { de: 'das Haus', ru: 'дом', example: 'Das Haus ist groß und hell.', category: 'Everyday' },
  { de: 'das Wasser', ru: 'вода', example: 'Ich trinke jeden Morgen Wasser.', category: 'Everyday' },
  { de: 'die Arbeit', ru: 'работа', example: 'Die Arbeit beginnt um neun Uhr.', category: 'Everyday' },
  { de: 'der Morgen', ru: 'утро', example: 'Der Morgen ist ruhig.', category: 'Everyday' },
  { de: 'der Abend', ru: 'вечер', example: 'Am Abend lerne ich Deutsch.', category: 'Everyday' },
  { de: 'die Zeit', ru: 'время', example: 'Ich habe heute wenig Zeit.', category: 'Everyday' },
  { de: 'die Familie', ru: 'семья', example: 'Meine Familie wohnt in der Stadt.', category: 'Everyday' },
  { de: 'der Freund', ru: 'друг', example: 'Mein Freund kommt aus Berlin.', category: 'Everyday' },
  { de: 'die Straße', ru: 'улица', example: 'Die Straße ist sehr lang.', category: 'Everyday' },
  { de: 'der Bahnhof', ru: 'вокзал', example: 'Der Bahnhof ist links.', category: 'Everyday' },
  { de: 'das Essen', ru: 'еда', example: 'Das Essen schmeckt gut.', category: 'Everyday' },
  { de: 'der Kaffee', ru: 'кофе', example: 'Der Kaffee ist heiß.', category: 'Everyday' },
  { de: 'das Brot', ru: 'хлеб', example: 'Das Brot ist frisch.', category: 'Everyday' },
  { de: 'die Uhr', ru: 'часы', example: 'Die Uhr zeigt acht Uhr.', category: 'Everyday' },
  { de: 'der Tag', ru: 'день', example: 'Der Tag ist schön.', category: 'Everyday' },
  { de: 'die Woche', ru: 'неделя', example: 'Die Woche hat sieben Tage.', category: 'Everyday' },
  { de: 'das Geld', ru: 'деньги', example: 'Ich brauche Geld für die Fahrkarte.', category: 'Everyday' },
  { de: 'die Frage', ru: 'вопрос', example: 'Ich habe eine Frage.', category: 'Everyday' },
  { de: 'die Antwort', ru: 'ответ', example: 'Die Antwort ist richtig.', category: 'Everyday' },
  { de: 'lernen', ru: 'учиться', example: 'Wir lernen jeden Tag Deutsch.', category: 'Everyday' },
  { de: 'der Computer', ru: 'компьютер', example: 'Der Computer startet schnell.', category: 'IT' },
  { de: 'die Software', ru: 'программное обеспечение', example: 'Die Software läuft stabil.', category: 'IT' },
  { de: 'das Netzwerk', ru: 'сеть', example: 'Das Netzwerk ist heute langsam.', category: 'IT' },
  { de: 'der Fehler', ru: 'ошибка', example: 'Der Fehler steht im Log.', category: 'IT' },
  { de: 'die Daten', ru: 'данные', example: 'Die Daten werden gespeichert.', category: 'IT' },
  { de: 'entwickeln', ru: 'разрабатывать', example: 'Wir entwickeln eine neue App.', category: 'IT' },
  { de: 'speichern', ru: 'сохранять', example: 'Bitte speichern Sie die Datei.', category: 'IT' },
  { de: 'der Server', ru: 'сервер', example: 'Der Server ist erreichbar.', category: 'IT' },
  { de: 'die Datenbank', ru: 'база данных', example: 'Die Datenbank enthält Kundendaten.', category: 'IT' },
  { de: 'das Passwort', ru: 'пароль', example: 'Das Passwort ist zu kurz.', category: 'IT' },
  { de: 'die Datei', ru: 'файл', example: 'Die Datei liegt im Ordner.', category: 'IT' },
  { de: 'der Ordner', ru: 'папка', example: 'Der Ordner ist leer.', category: 'IT' },
  { de: 'die Anwendung', ru: 'приложение', example: 'Die Anwendung reagiert nicht.', category: 'IT' },
  { de: 'der Bildschirm', ru: 'экран', example: 'Der Bildschirm bleibt schwarz.', category: 'IT' },
  { de: 'die Tastatur', ru: 'клавиатура', example: 'Die Tastatur funktioniert gut.', category: 'IT' },
  { de: 'die Cloud', ru: 'облако', example: 'Wir speichern Backups in der Cloud.', category: 'IT' },
  { de: 'das Backup', ru: 'резервная копия', example: 'Das Backup läuft nachts.', category: 'IT' },
  { de: 'die Verbindung', ru: 'соединение', example: 'Die Verbindung ist unterbrochen.', category: 'IT' },
  { de: 'aktualisieren', ru: 'обновлять', example: 'Wir aktualisieren das System.', category: 'IT' },
  { de: 'testen', ru: 'тестировать', example: 'Die Entwickler testen den Code.', category: 'IT' },
  { de: 'der Arzt', ru: 'врач', example: 'Der Arzt untersucht den Patienten.', category: 'Медицина' },
  { de: 'die Ärztin', ru: 'врач-женщина', example: 'Die Ärztin spricht mit der Patientin.', category: 'Медицина' },
  { de: 'das Krankenhaus', ru: 'больница', example: 'Das Krankenhaus ist in der Nähe.', category: 'Медицина' },
  { de: 'die Diagnose', ru: 'диагноз', example: 'Die Diagnose ist noch nicht klar.', category: 'Медицина' },
  { de: 'das Rezept', ru: 'рецепт', example: 'Der Arzt schreibt ein Rezept.', category: 'Медицина' },
  { de: 'die Symptome', ru: 'симптомы', example: 'Welche Symptome haben Sie?', category: 'Медицина' },
  { de: 'der Patient', ru: 'пациент', example: 'Der Patient hat Fieber.', category: 'Медицина' },
  { de: 'die Patientin', ru: 'пациентка', example: 'Die Patientin braucht Ruhe.', category: 'Медицина' },
  { de: 'die Untersuchung', ru: 'обследование', example: 'Die Untersuchung dauert zehn Minuten.', category: 'Медицина' },
  { de: 'die Schmerzen', ru: 'боли', example: 'Ich habe starke Schmerzen.', category: 'Медицина' },
  { de: 'das Fieber', ru: 'температура', example: 'Das Fieber ist hoch.', category: 'Медицина' },
  { de: 'die Tablette', ru: 'таблетка', example: 'Nehmen Sie eine Tablette nach dem Essen.', category: 'Медицина' },
  { de: 'die Apotheke', ru: 'аптека', example: 'Die Apotheke ist neben dem Krankenhaus.', category: 'Медицина' },
  { de: 'die Behandlung', ru: 'лечение', example: 'Die Behandlung beginnt heute.', category: 'Медицина' },
  { de: 'die Therapie', ru: 'терапия', example: 'Die Therapie hilft gut.', category: 'Медицина' },
  { de: 'der Termin', ru: 'приём', example: 'Ich habe einen Termin beim Arzt.', category: 'Медицина' },
  { de: 'die Versicherung', ru: 'страховка', example: 'Die Versicherung bezahlt die Behandlung.', category: 'Медицина' },
  { de: 'der Blutdruck', ru: 'кровяное давление', example: 'Der Blutdruck ist normal.', category: 'Медицина' },
  { de: 'der Notfall', ru: 'экстренный случай', example: 'Das ist ein medizinischer Notfall.', category: 'Медицина' },
  { de: 'husten', ru: 'кашлять', example: 'Ich huste seit drei Tagen.', category: 'Медицина' },
];

const lessonsData = [
  {
    id: 'lesson-greetings',
    title: 'Приветствия и знакомство',
    level: 'A1',
    category: 'Everyday',
    theory: `В немецком знакомстве важны короткие устойчивые формулы: Hallo, Guten Tag, Ich heiße... и Freut mich. Для нейтральной и вежливой речи используй Sie: Wie heißen Sie? Woher kommen Sie?

Если говоришь с коллегой или новым знакомым в неформальной ситуации, можно использовать du: Wie heißt du? Ich bin Thomas. В A1 достаточно назвать имя, страну и профессию одной-двумя простыми фразами.`,
    examples: [
      { de: 'Hallo, ich heiße Thomas.', ru: 'Привет, меня зовут Томас.' },
      { de: 'Guten Tag, wie heißen Sie?', ru: 'Добрый день, как вас зовут?' },
      { de: 'Ich komme aus Pakistan.', ru: 'Я из Пакистана.' },
      { de: 'Freut mich, Sie kennenzulernen.', ru: 'Приятно с вами познакомиться.' },
    ],
    quiz: [
      { question: 'Как перевести “Guten Tag”?', options: ['Добрый день', 'Доброй ночи', 'До свидания', 'Спасибо'], correct: 0 },
      { question: 'Выбери фразу “Меня зовут Томас”.', options: ['Ich heiße Thomas.', 'Ich habe Thomas.', 'Ich komme Thomas.', 'Ich bin aus Thomas.'], correct: 0 },
      { question: 'Что означает “Freut mich”?', options: ['Я устал', 'Приятно познакомиться', 'Где вокзал?', 'До завтра'], correct: 1 },
    ],
  },
  {
    id: 'lesson-numbers-time',
    title: 'Числа и время',
    level: 'A1',
    category: 'Everyday',
    theory: `Числа нужны для времени, цен, адресов и встреч. На старте выучи eins, zwei, drei, zehn, zwanzig и вопрос Wie spät ist es? — “Который час?”.

Для полного часа немецкий использует простую схему: Es ist acht Uhr. Для расписания и встреч добавляй um: Der Termin ist um neun Uhr. Это значит “в девять часов”.`,
    examples: [
      { de: 'Es ist acht Uhr.', ru: 'Сейчас восемь часов.' },
      { de: 'Der Termin ist um neun Uhr.', ru: 'Приём в девять часов.' },
      { de: 'Ich arbeite von acht bis fünf.', ru: 'Я работаю с восьми до пяти.' },
      { de: 'Wie spät ist es?', ru: 'Который час?' },
    ],
    quiz: [
      { question: 'Что значит “Wie spät ist es?”', options: ['Сколько это стоит?', 'Который час?', 'Как вас зовут?', 'Где работа?'], correct: 1 },
      { question: 'Как сказать “в девять часов”?', options: ['um neun Uhr', 'am neun Uhr', 'in neun Uhr', 'von neun Uhr'], correct: 0 },
      { question: 'Как переводится “zehn”?', options: ['три', 'пять', 'десять', 'двадцать'], correct: 2 },
    ],
  },
  {
    id: 'lesson-it-workday',
    title: 'IT: рабочий день программиста',
    level: 'A1',
    category: 'IT',
    theory: `В IT-немецком на A1 полезны слова der Computer, die Software, der Fehler, die Daten и глаголы entwickeln, testen, speichern. С ними можно описать рабочий день очень простыми предложениями.

Порядок слов в обычном предложении: подлежащее + глагол + остальная информация. Например: Ich entwickle eine App. Wir testen den Code. Если говоришь о проблеме, используй Es gibt einen Fehler — “есть ошибка”.`,
    examples: [
      { de: 'Ich entwickle eine App.', ru: 'Я разрабатываю приложение.' },
      { de: 'Wir testen den Code.', ru: 'Мы тестируем код.' },
      { de: 'Ich speichere die Daten.', ru: 'Я сохраняю данные.' },
      { de: 'Es gibt einen Fehler im Programm.', ru: 'В программе есть ошибка.' },
    ],
    quiz: [
      { question: 'Как переводится “der Fehler”?', options: ['сервер', 'ошибка', 'экран', 'папка'], correct: 1 },
      { question: 'Выбери “Мы тестируем код”.', options: ['Wir testen den Code.', 'Wir speichern den Kaffee.', 'Der Code testet uns.', 'Ich teste die Uhr.'], correct: 0 },
      { question: 'Что значит “speichern”?', options: ['сохранять', 'лечить', 'знакомиться', 'покупать'], correct: 0 },
    ],
  },
  {
    id: 'lesson-doctor',
    title: 'Медицина: у врача',
    level: 'A1',
    category: 'Медицина',
    theory: `На приёме у врача важно коротко описать состояние: Ich habe Schmerzen, Ich habe Fieber, Mir ist nicht gut. Врач часто спрашивает Seit wann? — “С каких пор?”.

Для базового диалога хватит слов der Arzt, der Patient, die Symptome, die Untersuchung и das Rezept. После осмотра можно услышать: Ich schreibe ein Rezept — “Я выпишу рецепт”.`,
    examples: [
      { de: 'Ich habe Schmerzen.', ru: 'У меня боли.' },
      { de: 'Seit wann haben Sie Fieber?', ru: 'С каких пор у вас температура?' },
      { de: 'Der Arzt untersucht den Patienten.', ru: 'Врач осматривает пациента.' },
      { de: 'Ich brauche ein Rezept.', ru: 'Мне нужен рецепт.' },
    ],
    quiz: [
      { question: 'Что значит “die Symptome”?', options: ['страховка', 'симптомы', 'сеть', 'ответ'], correct: 1 },
      { question: 'Как сказать “У меня температура”?', options: ['Ich habe Fieber.', 'Ich bin Rezept.', 'Ich mache Arzt.', 'Ich speichere Fieber.'], correct: 0 },
      { question: 'Как переводится “das Krankenhaus”?', options: ['аптека', 'больница', 'приём', 'таблетка'], correct: 1 },
    ],
  },
];

const lessonColors = ['c-gold', 'c-green', 'c-blue', 'c-teal'];
const lessonGermanTitles = {
  'lesson-greetings': 'Begrüßung und Vorstellung',
  'lesson-numbers-time': 'Zahlen und Uhrzeit',
  'lesson-it-workday': 'IT-Arbeitstag',
  'lesson-doctor': 'Beim Arzt',
};

const GENERAL_LESSONS = [
  { id:'g1', title:'Знакомство', de:'Vorstellung', color:'c-gold', type:'Базовый A1',
    words:[
      {de:'Hallo',ru:'Привет',ex:'Hallo! Wie geht\'s?',cat:'general'},
      {de:'Ich bin',ru:'Я / Меня зовут',ex:'Ich bin Thomas.',cat:'general'},
      {de:'mein Name',ru:'моё имя',ex:'Mein Name ist Thomas.',cat:'general'},
      {de:'Woher kommen Sie?',ru:'Откуда вы?',ex:'Ich komme aus Tadschikistan.',cat:'general'},
      {de:'Freut mich',ru:'Приятно познакомиться',ex:'Freut mich!',cat:'general'},
      {de:'Guten Tag',ru:'Добрый день',ex:'Guten Tag, Herr Müller.',cat:'general'},
      {de:'Auf Wiedersehen',ru:'До свидания',ex:'Auf Wiedersehen!',cat:'general'},
      {de:'Wie geht es Ihnen?',ru:'Как у вас дела?',ex:'Wie geht es Ihnen?',cat:'general'},
      {de:'Danke, gut',ru:'Спасибо, хорошо',ex:'Danke, gut.',cat:'general'},
      {de:'Entschuldigung',ru:'Извините',ex:'Entschuldigung!',cat:'general'},
    ],
    quiz:[
      {q:'Hallo',opts:['Пока','Привет','Спасибо','Да'],a:1},
      {q:'mein Name',opts:['мой дом','моё имя','мой город','мой друг'],a:1},
    ]
  },
  { id:'g2', title:'Числа 1–100', de:'Zahlen', color:'c-green', type:'Базовый A1',
    words:[
      {de:'eins',ru:'один',ex:'Ich habe eins.',cat:'general'},
      {de:'zwei',ru:'два',ex:'Zwei Kaffee, bitte.',cat:'general'},
      {de:'drei',ru:'три',ex:'Drei Personen.',cat:'general'},
      {de:'vier',ru:'четыре',ex:'Vier Tage.',cat:'general'},
      {de:'fünf',ru:'пять',ex:'Fünf Euro.',cat:'general'},
      {de:'sechs',ru:'шесть',ex:'Sechs Monate.',cat:'general'},
      {de:'sieben',ru:'семь',ex:'Sieben Jahre.',cat:'general'},
      {de:'acht',ru:'восемь',ex:'Acht Stunden.',cat:'general'},
      {de:'neun',ru:'девять',ex:'Neun Bücher.',cat:'general'},
      {de:'zehn',ru:'десять',ex:'Es ist zehn Uhr.',cat:'general'},
      {de:'elf',ru:'одиннадцать',ex:'Elf Uhr.',cat:'general'},
      {de:'zwölf',ru:'двенадцать',ex:'Zwölf Monate.',cat:'general'},
      {de:'dreizehn',ru:'тринадцать',ex:'Dreizehn.',cat:'general'},
      {de:'vierzehn',ru:'четырнадцать',ex:'Vierzehn.',cat:'general'},
      {de:'fünfzehn',ru:'пятнадцать',ex:'Fünfzehn.',cat:'general'},
      {de:'sechzehn',ru:'шестнадцать',ex:'Sechzehn.',cat:'general'},
      {de:'siebzehn',ru:'семнадцать',ex:'Siebzehn.',cat:'general'},
      {de:'achtzehn',ru:'восемнадцать',ex:'Achtzehn.',cat:'general'},
      {de:'neunzehn',ru:'девятнадцать',ex:'Neunzehn.',cat:'general'},
      {de:'zwanzig',ru:'двадцать',ex:'Ich bin zwanzig.',cat:'general'},
      {de:'einundzwanzig',ru:'двадцать один',ex:'Einundzwanzig.',cat:'general'},
      {de:'dreißig',ru:'тридцать',ex:'Dreißig Euro.',cat:'general'},
      {de:'vierzig',ru:'сорок',ex:'Vierzig.',cat:'general'},
      {de:'fünfzig',ru:'пятьдесят',ex:'Fünfzig.',cat:'general'},
      {de:'sechzig',ru:'шестьдесят',ex:'Sechzig.',cat:'general'},
      {de:'siebzig',ru:'семьдесят',ex:'Siebzig.',cat:'general'},
      {de:'achtzig',ru:'восемьдесят',ex:'Achtzig.',cat:'general'},
      {de:'neunzig',ru:'девяносто',ex:'Neunzig.',cat:'general'},
      {de:'hundert',ru:'сто',ex:'Hundert Euro.',cat:'general'},
    ],
    quiz:[
      {q:'zehn',opts:['двадцать','десять','семь','три'],a:1},
      {q:'hundert',opts:['тысяча','сто','миллион','десять'],a:1},
    ]
  },
  { id:'g3', title:'Семья', de:'Familie', color:'c-blue', type:'A1',
    words:[
      {de:'die Mutter',ru:'мама',ex:'Meine Mutter heißt...',cat:'general'},
      {de:'der Vater',ru:'папа',ex:'Mein Vater arbeitet.',cat:'general'},
      {de:'der Bruder',ru:'брат',ex:'Ich habe einen Bruder.',cat:'general'},
      {de:'die Schwester',ru:'сестра',ex:'Meine Schwester ist jung.',cat:'general'},
    ],
    quiz:[
      {q:'die Mutter',opts:['папа','сестра','мама','дядя'],a:2},
      {q:'der Bruder',opts:['дядя','брат','муж','сын'],a:1},
    ]
  },
  { id:'g4', title:'Время и дни', de:'Zeit & Wochentage', color:'c-purple', type:'A1',
    words:[
      {de:'heute',ru:'сегодня',ex:'Heute ist Montag.',cat:'general'},
      {de:'morgen',ru:'завтра',ex:'Morgen gehe ich.',cat:'general'},
      {de:'der Montag',ru:'понедельник',ex:'Am Montag arbeite ich.',cat:'general'},
      {de:'das Wochenende',ru:'выходные',ex:'Am Wochenende schlafe ich.',cat:'general'},
    ],
    quiz:[
      {q:'heute',opts:['завтра','вчера','сегодня','сейчас'],a:2},
      {q:'der Montag',opts:['пятница','воскресенье','понедельник','среда'],a:2},
    ]
  },
  { id:'g5', title:'Еда и напитки', de:'Essen & Trinken', color:'c-teal', type:'A1',
    words:[
      {de:'das Brot',ru:'хлеб',ex:'Das Brot ist frisch.',cat:'general'},
      {de:'der Kaffee',ru:'кофе',ex:'Ich trinke Kaffee.',cat:'general'},
      {de:'das Wasser',ru:'вода',ex:'Ich möchte Wasser.',cat:'general'},
      {de:'das Fleisch',ru:'мясо',ex:'Das Fleisch ist gut.',cat:'general'},
    ],
    quiz:[
      {q:'das Brot',opts:['молоко','хлеб','мясо','кофе'],a:1},
    ]
  },
  { id:'g6', title:'Грамматика: Артикли', de:'der/die/das', color:'c-orange', type:'A1',
    words:[
      {de:'der',ru:'артикль (муж.)',ex:'der Mann, der Tisch',cat:'general'},
      {de:'die',ru:'артикль (жен./мн.ч.)',ex:'die Frau, die Kinder',cat:'general'},
      {de:'das',ru:'артикль (ср.р.)',ex:'das Kind, das Haus',cat:'general'},
      {de:'ein / eine',ru:'неопр. артикль',ex:'ein Mann, eine Frau',cat:'general'},
    ],
    quiz:[
      {q:'Какой артикль у "Kind" (ребёнок)?',opts:['der','die','das','ein'],a:2},
      {q:'Какой артикль у "Frau" (женщина)?',opts:['der','die','das','ein'],a:1},
    ]
  },
  { id:'g7', title:'Цвета', de:'Farben', color:'c-red', type:'A1',
    words:[
      {de:'rot',ru:'красный',ex:'Das Auto ist rot.',cat:'general'},
      {de:'blau',ru:'синий',ex:'Der Himmel ist blau.',cat:'general'},
      {de:'grün',ru:'зелёный',ex:'Das Gras ist grün.',cat:'general'},
      {de:'gelb',ru:'жёлтый',ex:'Die Sonne ist gelb.',cat:'general'},
      {de:'schwarz',ru:'чёрный',ex:'Die Katze ist schwarz.',cat:'general'},
      {de:'weiß',ru:'белый',ex:'Der Schnee ist weiß.',cat:'general'},
    ],
    quiz:[
      {q:'rot',opts:['синий','красный','зелёный','жёлтый'],a:1},
      {q:'blau',opts:['красный','синий','чёрный','белый'],a:1},
    ]
  },
  { id:'g8', title:'Профессии', de:'Berufe', color:'c-brown', type:'A1',
    words:[
      {de:'der Arzt',ru:'врач',ex:'Mein Bruder ist Arzt.',cat:'general'},
      {de:'der Lehrer',ru:'учитель',ex:'Die Lehrerin ist nett.',cat:'general'},
      {de:'der Ingenieur',ru:'инженер',ex:'Er arbeitet als Ingenieur.',cat:'general'},
      {de:'die Krankenschwester',ru:'медсестра',ex:'Die Krankenschwester hilft.',cat:'general'},
      {de:'der Koch',ru:'повар',ex:'Der Koch kocht Essen.',cat:'general'},
    ],
    quiz:[
      {q:'der Arzt',opts:['учитель','врач','инженер','повар'],a:1},
      {q:'die Krankenschwester',opts:['врач','медсестра','учитель','инженер'],a:1},
    ]
  },
  { id:'g9', title:'Город и транспорт', de:'Stadt & Verkehr', color:'c-gray', type:'A1',
    words:[
      {de:'die Stadt',ru:'город',ex:'Ich lebe in der Stadt.',cat:'general'},
      {de:'das Auto',ru:'машина',ex:'Das Auto fährt schnell.',cat:'general'},
      {de:'der Bus',ru:'автобус',ex:'Der Bus kommt.',cat:'general'},
      {de:'die Straße',ru:'улица',ex:'Die Straße ist breit.',cat:'general'},
      {de:'der Bahnhof',ru:'вокзал',ex:'Am Bahnhof warten.',cat:'general'},
    ],
    quiz:[
      {q:'die Stadt',opts:['деревня','город','улица','дом'],a:1},
      {q:'das Auto',opts:['велосипед','машина','автобус','поезд'],a:1},
    ]
  },
  { id:'g10', title:'Дом и мебель', de:'Haus & Möbel', color:'c-pink', type:'A1',
    words:[
      {de:'das Haus',ru:'дом',ex:'Das Haus ist groß.',cat:'general'},
      {de:'die Küche',ru:'кухня',ex:'In der Küche koche ich.',cat:'general'},
      {de:'das Zimmer',ru:'комната',ex:'Mein Zimmer ist klein.',cat:'general'},
      {de:'der Tisch',ru:'стол',ex:'Der Tisch ist rund.',cat:'general'},
      {de:'der Stuhl',ru:'стул',ex:'Der Stuhl ist bequem.',cat:'general'},
    ],
    quiz:[
      {q:'das Haus',opts:['квартира','дом','комната','кухня'],a:1},
      {q:'der Tisch',opts:['стул','стол','кровать','шкаф'],a:1},
    ]
  },
  // A2 lessons
  { id:'g11', title:'Повседневные глаголы', de:'Alltagsverben', color:'c-gold', type:'A2',
    words:[
      {de:'essen',ru:'есть',ex:'Ich esse Brot.',cat:'general'},
      {de:'trinken',ru:'пить',ex:'Ich trinke Wasser.',cat:'general'},
      {de:'schlafen',ru:'спать',ex:'Ich schlafe gut.',cat:'general'},
      {de:'arbeiten',ru:'работать',ex:'Er arbeitet viel.',cat:'general'},
      {de:'lernen',ru:'учиться',ex:'Ich lerne Deutsch.',cat:'general'},
    ],
    quiz:[
      {q:'essen',opts:['пить','есть','спать','работать'],a:1},
      {q:'lernen',opts:['работать','учиться','спать','пить'],a:1},
    ]
  },
  { id:'g12', title:'Времена года', de:'Jahreszeiten', color:'c-green', type:'A2',
    words:[
      {de:'der Frühling',ru:'весна',ex:'Im Frühling blühen Blumen.',cat:'general'},
      {de:'der Sommer',ru:'лето',ex:'Im Sommer ist es heiß.',cat:'general'},
      {de:'der Herbst',ru:'осень',ex:'Im Herbst fallen Blätter.',cat:'general'},
      {de:'der Winter',ru:'зима',ex:'Im Winter schneit es.',cat:'general'},
    ],
    quiz:[
      {q:'der Sommer',opts:['зима','лето','осень','весна'],a:1},
      {q:'der Winter',opts:['весна','осень','зима','лето'],a:2},
    ]
  },
  { id:'g13', title:'Погода', de:'Wetter', color:'c-blue', type:'A2',
    words:[
      {de:'sonnig',ru:'солнечно',ex:'Heute ist sonnig.',cat:'general'},
      {de:'regnerisch',ru:'дождливо',ex:'Es ist regnerisch.',cat:'general'},
      {de:'kalt',ru:'холодно',ex:'Es ist kalt draußen.',cat:'general'},
      {de:'warm',ru:'тепло',ex:'Es ist warm.',cat:'general'},
    ],
    quiz:[
      {q:'sonnig',opts:['дождливо','солнечно','холодно','тепло'],a:1},
      {q:'kalt',opts:['тепло','солнечно','холодно','дождливо'],a:2},
    ]
  },
  { id:'g14', title:'Магазины', de:'Einkaufen', color:'c-purple', type:'A2',
    words:[
      {de:'der Laden',ru:'магазин',ex:'Ich gehe in den Laden.',cat:'general'},
      {de:'kaufen',ru:'покупать',ex:'Ich kaufe Brot.',cat:'general'},
      {de:'teuer',ru:'дорогой',ex:'Das ist teuer.',cat:'general'},
      {de:'billig',ru:'дешёвый',ex:'Das ist billig.',cat:'general'},
    ],
    quiz:[
      {q:'kaufen',opts:['продавать','покупать','платить','идти'],a:1},
      {q:'teuer',opts:['дешёвый','дорогой','большой','маленький'],a:1},
    ]
  },
  { id:'g15', title:'Здоровье', de:'Gesundheit', color:'c-teal', type:'A2',
    words:[
      {de:'krank',ru:'больной',ex:'Ich bin krank.',cat:'general'},
      {de:'gesund',ru:'здоровый',ex:'Er ist gesund.',cat:'general'},
      {de:'der Schmerz',ru:'боль',ex:'Ich habe Schmerzen.',cat:'general'},
      {de:'die Apotheke',ru:'аптека',ex:'Gehe zur Apotheke.',cat:'general'},
    ],
    quiz:[
      {q:'krank',opts:['здоровый','больной','усталый','голодный'],a:1},
      {q:'gesund',opts:['больной','здоровый','счастливый','грустный'],a:1},
    ]
  },
  // B1 lessons
  { id:'g16', title:'Будущее время', de:'Futur', color:'c-orange', type:'B1',
    words:[
      {de:'werden',ru:'становиться',ex:'Ich werde Arzt.',cat:'general'},
      {de:'morgen',ru:'завтра',ex:'Morgen komme ich.',cat:'general'},
      {de:'nächste Woche',ru:'на следующей неделе',ex:'Nächste Woche fahre ich.',cat:'general'},
    ],
    quiz:[
      {q:'werden',opts:['быть','становиться','идти','делать'],a:1},
    ]
  },
  { id:'g17', title:'Прошедшее время', de:'Perfekt', color:'c-red', type:'B1',
    words:[
      {de:'haben',ru:'иметь',ex:'Ich habe gegessen.',cat:'general'},
      {de:'sein',ru:'быть',ex:'Ich bin gegangen.',cat:'general'},
      {de:'gegessen',ru:'съел',ex:'Ich habe gegessen.',cat:'general'},
    ],
    quiz:[
      {q:'haben',opts:['быть','иметь','делать','идти'],a:1},
    ]
  },
  { id:'g18', title:'Модальные глаголы', de:'Modalverben', color:'c-brown', type:'B1',
    words:[
      {de:'können',ru:'мочь',ex:'Ich kann schwimmen.',cat:'general'},
      {de:'müssen',ru:'должен',ex:'Ich muss arbeiten.',cat:'general'},
      {de:'wollen',ru:'хотеть',ex:'Ich will essen.',cat:'general'},
    ],
    quiz:[
      {q:'können',opts:['должен','хотеть','мочь','идти'],a:2},
      {q:'müssen',opts:['мочь','должен','хотеть','делать'],a:1},
    ]
  },
  { id:'g19', title:'Общие слова A1', de:'Allgemeine Wörter A1', color:'c-teal', type:'A1',
    words:[
      {de:'der Mann',ru:'мужчина',ex:'Der Mann ist groß.',cat:'general'},
      {de:'die Frau',ru:'женщина',ex:'Die Frau ist schön.',cat:'general'},
      {de:'das Kind',ru:'ребёнок',ex:'Das Kind spielt.',cat:'general'},
      {de:'der Junge',ru:'мальчик',ex:'Der Junge läuft.',cat:'general'},
      {de:'das Mädchen',ru:'девочка',ex:'Das Mädchen singt.',cat:'general'},
      {de:'der Hund',ru:'собака',ex:'Der Hund bellt.',cat:'general'},
      {de:'die Katze',ru:'кошка',ex:'Die Katze schläft.',cat:'general'},
      {de:'das Buch',ru:'книга',ex:'Das Buch ist interessant.',cat:'general'},
      {de:'der Tisch',ru:'стол',ex:'Der Tisch ist rund.',cat:'general'},
      {de:'der Stuhl',ru:'стул',ex:'Der Stuhl ist bequem.',cat:'general'},
      {de:'das Haus',ru:'дом',ex:'Das Haus ist groß.',cat:'general'},
      {de:'die Tür',ru:'дверь',ex:'Die Tür ist offen.',cat:'general'},
      {de:'das Fenster',ru:'окно',ex:'Das Fenster ist groß.',cat:'general'},
      {de:'die Straße',ru:'улица',ex:'Die Straße ist breit.',cat:'general'},
      {de:'das Auto',ru:'машина',ex:'Das Auto fährt.',cat:'general'},
      {de:'der Bus',ru:'автобус',ex:'Der Bus kommt.',cat:'general'},
      {de:'der Zug',ru:'поезд',ex:'Der Zug fährt schnell.',cat:'general'},
      {de:'das Flugzeug',ru:'самолёт',ex:'Das Flugzeug fliegt.',cat:'general'},
      {de:'das Essen',ru:'еда',ex:'Das Essen ist gut.',cat:'general'},
      {de:'das Trinken',ru:'напиток',ex:'Das Trinken ist kalt.',cat:'general'},
      {de:'das Wasser',ru:'вода',ex:'Ich trinke Wasser.',cat:'general'},
      {de:'der Kaffee',ru:'кофе',ex:'Der Kaffee ist heiß.',cat:'general'},
      {de:'der Tee',ru:'чай',ex:'Der Tee ist grün.',cat:'general'},
      {de:'das Brot',ru:'хлеб',ex:'Das Brot ist frisch.',cat:'general'},
      {de:'der Käse',ru:'сыр',ex:'Der Käse ist gelb.',cat:'general'},
      {de:'die Milch',ru:'молоко',ex:'Die Milch ist kalt.',cat:'general'},
      {de:'das Obst',ru:'фрукт',ex:'Das Obst ist süß.',cat:'general'},
      {de:'der Apfel',ru:'яблоко',ex:'Der Apfel ist rot.',cat:'general'},
      {de:'die Banane',ru:'банан',ex:'Die Banane ist gelb.',cat:'general'},
      {de:'die Orange',ru:'апельсин',ex:'Die Orange ist orange.',cat:'general'},
      {de:'die Schule',ru:'школа',ex:'Die Schule ist nah.',cat:'general'},
      {de:'der Lehrer',ru:'учитель',ex:'Der Lehrer erklärt.',cat:'general'},
      {de:'der Schüler',ru:'ученик',ex:'Der Schüler lernt.',cat:'general'},
      {de:'die Arbeit',ru:'работа',ex:'Die Arbeit ist schwer.',cat:'general'},
      {de:'der Chef',ru:'шеф',ex:'Der Chef ist streng.',cat:'general'},
      {de:'der Kollege',ru:'коллега',ex:'Der Kollege hilft.',cat:'general'},
      {de:'die Zeit',ru:'время',ex:'Die Zeit vergeht.',cat:'general'},
      {de:'die Uhr',ru:'часы',ex:'Die Uhr tickt.',cat:'general'},
      {de:'der Tag',ru:'день',ex:'Der Tag ist schön.',cat:'general'},
      {de:'die Nacht',ru:'ночь',ex:'Die Nacht ist dunkel.',cat:'general'},
      {de:'der Morgen',ru:'утро',ex:'Der Morgen ist früh.',cat:'general'},
      {de:'der Abend',ru:'вечер',ex:'Der Abend ist spät.',cat:'general'},
      {de:'die Woche',ru:'неделя',ex:'Die Woche hat 7 Tage.',cat:'general'},
      {de:'der Monat',ru:'месяц',ex:'Der Monat ist lang.',cat:'general'},
      {de:'das Jahr',ru:'год',ex:'Das Jahr hat 12 Monate.',cat:'general'},
      {de:'der Frühling',ru:'весна',ex:'Im Frühling blühen Blumen.',cat:'general'},
      {de:'der Sommer',ru:'лето',ex:'Im Sommer ist es heiß.',cat:'general'},
      {de:'der Herbst',ru:'осень',ex:'Im Herbst fallen Blätter.',cat:'general'},
      {de:'der Winter',ru:'зима',ex:'Im Winter schneit es.',cat:'general'},
      {de:'sonnig',ru:'солнечно',ex:'Heute ist sonnig.',cat:'general'},
      {de:'regnerisch',ru:'дождливо',ex:'Es ist regnerisch.',cat:'general'},
      {de:'kalt',ru:'холодно',ex:'Es ist kalt.',cat:'general'},
      {de:'warm',ru:'тепло',ex:'Es ist warm.',cat:'general'},
      {de:'groß',ru:'большой',ex:'Das Haus ist groß.',cat:'general'},
      {de:'klein',ru:'маленький',ex:'Das Kind ist klein.',cat:'general'},
      {de:'lang',ru:'длинный',ex:'Der Tisch ist lang.',cat:'general'},
      {de:'kurz',ru:'короткий',ex:'Der Rock ist kurz.',cat:'general'},
      {de:'neu',ru:'новый',ex:'Das Auto ist neu.',cat:'general'},
      {de:'alt',ru:'старый',ex:'Das Buch ist alt.',cat:'general'},
      {de:'gut',ru:'хороший',ex:'Das Essen ist gut.',cat:'general'},
      {de:'schlecht',ru:'плохой',ex:'Das Wetter ist schlecht.',cat:'general'},
      {de:'schnell',ru:'быстрый',ex:'Der Zug ist schnell.',cat:'general'},
      {de:'langsam',ru:'медленный',ex:'Der Bus ist langsam.',cat:'general'},
      {de:'richtig',ru:'правильный',ex:'Das ist richtig.',cat:'general'},
      {de:'falsch',ru:'неправильный',ex:'Das ist falsch.',cat:'general'},
      {de:'hier',ru:'здесь',ex:'Ich bin hier.',cat:'general'},
      {de:'dort',ru:'там',ex:'Das Buch ist dort.',cat:'general'},
      {de:'links',ru:'слева',ex:'Links ist die Tür.',cat:'general'},
      {de:'rechts',ru:'справа',ex:'Rechts ist das Fenster.',cat:'general'},
      {de:'oben',ru:'сверху',ex:'Oben ist der Himmel.',cat:'general'},
      {de:'unten',ru:'снизу',ex:'Unten ist der Boden.',cat:'general'},
      {de:'viel',ru:'много',ex:'Ich habe viel Arbeit.',cat:'general'},
      {de:'wenig',ru:'мало',ex:'Ich habe wenig Zeit.',cat:'general'},
      {de:'immer',ru:'всегда',ex:'Ich komme immer pünktlich.',cat:'general'},
      {de:'nie',ru:'никогда',ex:'Ich komme nie spät.',cat:'general'},
      {de:'oft',ru:'часто',ex:'Ich gehe oft spazieren.',cat:'general'},
      {de:'selten',ru:'редко',ex:'Ich esse selten Fleisch.',cat:'general'},
      {de:'jetzt',ru:'сейчас',ex:'Jetzt ist es Zeit.',cat:'general'},
      {de:'später',ru:'позже',ex:'Später gehe ich.',cat:'general'},
      {de:'früher',ru:'раньше',ex:'Früher war es anders.',cat:'general'},
      {de:'gestern',ru:'вчера',ex:'Gestern war ich krank.',cat:'general'},
      {de:'morgen',ru:'завтра',ex:'Morgen komme ich.',cat:'general'},
      {de:'kommen',ru:'приходить',ex:'Ich komme nach Hause.',cat:'general'},
      {de:'gehen',ru:'идти',ex:'Ich gehe zur Schule.',cat:'general'},
      {de:'fahren',ru:'ехать',ex:'Ich fahre mit dem Auto.',cat:'general'},
      {de:'fliegen',ru:'летать',ex:'Das Flugzeug fliegt.',cat:'general'},
      {de:'sprechen',ru:'говорить',ex:'Ich spreche Deutsch.',cat:'general'},
      {de:'lesen',ru:'читать',ex:'Ich lese ein Buch.',cat:'general'},
      {de:'schreiben',ru:'писать',ex:'Ich schreibe einen Brief.',cat:'general'},
      {de:'sehen',ru:'видеть',ex:'Ich sehe den Hund.',cat:'general'},
      {de:'hören',ru:'слышать',ex:'Ich höre Musik.',cat:'general'},
      {de:'machen',ru:'делать',ex:'Ich mache Hausaufgaben.',cat:'general'},
      {de:'haben',ru:'иметь',ex:'Ich habe ein Buch.',cat:'general'},
      {de:'sein',ru:'быть',ex:'Ich bin müde.',cat:'general'},
      {de:'werden',ru:'становиться',ex:'Ich werde Arzt.',cat:'general'},
      {de:'können',ru:'мочь',ex:'Ich kann schwimmen.',cat:'general'},
      {de:'müssen',ru:'должен',ex:'Ich muss arbeiten.',cat:'general'},
      {de:'wollen',ru:'хотеть',ex:'Ich will essen.',cat:'general'},
      {de:'mögen',ru:'нравиться',ex:'Ich mag Musik.',cat:'general'},
      {de:'lieben',ru:'любить',ex:'Ich liebe dich.',cat:'general'},
      {de:'hassen',ru:'ненавидеть',ex:'Ich hasse Regen.',cat:'general'},
    ],
    quiz:[
      {q:'der Mann',opts:['женщина','мужчина','ребёнок','собака'],a:1},
      {q:'das Haus',opts:['улица','дом','машина','школа'],a:1},
    ]
  },
  { id:'g20', title:'Продвинутые слова A2-B1', de:'Fortgeschrittene Wörter A2-B1', color:'c-purple', type:'A2-B1',
    words:[
      {de:'die Möglichkeit',ru:'возможность',ex:'Es gibt eine Möglichkeit.',cat:'general'},
      {de:'die Entscheidung',ru:'решение',ex:'Die Entscheidung ist gefallen.',cat:'general'},
      {de:'die Erfahrung',ru:'опыт',ex:'Ich habe Erfahrung.',cat:'general'},
      {de:'die Bedeutung',ru:'значение',ex:'Das hat Bedeutung.',cat:'general'},
      {de:'die Entwicklung',ru:'развитие',ex:'Die Entwicklung ist schnell.',cat:'general'},
      {de:'die Situation',ru:'ситуация',ex:'Die Situation ist kompliziert.',cat:'general'},
      {de:'die Frage',ru:'вопрос',ex:'Das ist eine gute Frage.',cat:'general'},
      {de:'die Antwort',ru:'ответ',ex:'Die Antwort ist klar.',cat:'general'},
      {de:'die Information',ru:'информация',ex:'Ich brauche Information.',cat:'general'},
      {de:'die Kommunikation',ru:'коммуникация',ex:'Die Kommunikation ist wichtig.',cat:'general'},
      {de:'die Organisation',ru:'организация',ex:'Die Organisation ist gut.',cat:'general'},
      {de:'die Produktion',ru:'производство',ex:'Die Produktion läuft.',cat:'general'},
      {de:'die Qualität',ru:'качество',ex:'Die Qualität ist hoch.',cat:'general'},
      {de:'die Quantität',ru:'количество',ex:'Die Quantität ist groß.',cat:'general'},
      {de:'die Realität',ru:'реальность',ex:'Das ist die Realität.',cat:'general'},
      {de:'die Sicherheit',ru:'безопасность',ex:'Sicherheit geht vor.',cat:'general'},
      {de:'die Technologie',ru:'технология',ex:'Die Technologie entwickelt sich.',cat:'general'},
      {de:'die Umwelt',ru:'окружающая среда',ex:'Die Umwelt schützen.',cat:'general'},
      {de:'die Verantwortung',ru:'ответственность',ex:'Das ist meine Verantwortung.',cat:'general'},
      {de:'die Zukunft',ru:'будущее',ex:'Die Zukunft ist ungewiss.',cat:'general'},
      {de:'der Grund',ru:'причина',ex:'Der Grund ist klar.',cat:'general'},
      {de:'der Unterschied',ru:'разница',ex:'Der Unterschied ist groß.',cat:'general'},
      {de:'der Vorteil',ru:'преимущество',ex:'Das ist ein Vorteil.',cat:'general'},
      {de:'der Nachteil',ru:'недостаток',ex:'Das ist ein Nachteil.',cat:'general'},
      {de:'der Erfolg',ru:'успех',ex:'Der Erfolg ist da.',cat:'general'},
      {de:'der Misserfolg',ru:'неудача',ex:'Das ist ein Misserfolg.',cat:'general'},
      {de:'der Anfang',ru:'начало',ex:'Der Anfang ist schwer.',cat:'general'},
      {de:'das Ende',ru:'конец',ex:'Das Ende ist nah.',cat:'general'},
      {de:'der Teil',ru:'часть',ex:'Das ist ein Teil.',cat:'general'},
      {de:'das Ganze',ru:'целое',ex:'Das Ganze ist wichtig.',cat:'general'},
      {de:'die Gruppe',ru:'группа',ex:'Die Gruppe ist groß.',cat:'general'},
      {de:'die Menge',ru:'толпа',ex:'Eine Menge Leute.',cat:'general'},
      {de:'die Reihe',ru:'ряд',ex:'In der Reihe stehen.',cat:'general'},
      {de:'die Serie',ru:'серия',ex:'Eine Serie schauen.',cat:'general'},
      {de:'die Summe',ru:'сумма',ex:'Die Summe ist hoch.',cat:'general'},
      {de:'die Zahl',ru:'число',ex:'Eine hohe Zahl.',cat:'general'},
      {de:'die Art',ru:'вид',ex:'Eine Art von...',cat:'general'},
      {de:'die Form',ru:'форма',ex:'Die Form ist rund.',cat:'general'},
      {de:'die Größe',ru:'размер',ex:'Die Größe passt.',cat:'general'},
      {de:'die Höhe',ru:'высота',ex:'Die Höhe ist 10m.',cat:'general'},
      {de:'die Länge',ru:'длина',ex:'Die Länge ist 5m.',cat:'general'},
      {de:'die Breite',ru:'ширина',ex:'Die Breite ist 2m.',cat:'general'},
      {de:'die Tiefe',ru:'глубина',ex:'Die Tiefe ist groß.',cat:'general'},
      {de:'die Richtung',ru:'направление',ex:'In diese Richtung.',cat:'general'},
      {de:'die Seite',ru:'сторона',ex:'Auf der anderen Seite.',cat:'general'},
      {de:'die Mitte',ru:'середина',ex:'In der Mitte.',cat:'general'},
      {de:'der Ort',ru:'место',ex:'An diesem Ort.',cat:'general'},
      {de:'der Platz',ru:'площадь',ex:'Auf dem Platz.',cat:'general'},
      {de:'der Raum',ru:'пространство',ex:'Genug Raum.',cat:'general'},
      {de:'die Stelle',ru:'место',ex:'An dieser Stelle.',cat:'general'},
      {de:'die Position',ru:'позиция',ex:'Eine gute Position.',cat:'general'},
      {de:'die Lage',ru:'положение',ex:'Die Lage ist schlecht.',cat:'general'},
      {de:'die Bewegung',ru:'движение',ex:'Eine schnelle Bewegung.',cat:'general'},
      {de:'die Geschwindigkeit',ru:'скорость',ex:'Hohe Geschwindigkeit.',cat:'general'},
      {de:'die Kraft',ru:'сила',ex:'Mit voller Kraft.',cat:'general'},
      {de:'die Energie',ru:'энергия',ex:'Erneuerbare Energie.',cat:'general'},
      {de:'die Macht',ru:'власть',ex:'Die Macht haben.',cat:'general'},
      {de:'die Freiheit',ru:'свобода',ex:'Freiheit ist wichtig.',cat:'general'},
      {de:'die Gleichheit',ru:'равенство',ex:'Gleichheit für alle.',cat:'general'},
      {de:'die Gerechtigkeit',ru:'справедливость',ex:'Gerechtigkeit walten.',cat:'general'},
      {de:'die Wahrheit',ru:'правда',ex:'Die Wahrheit sagen.',cat:'general'},
      {de:'die Lüge',ru:'ложь',ex:'Das ist eine Lüge.',cat:'general'},
      {de:'die Hoffnung',ru:'надежда',ex:'Hoffnung haben.',cat:'general'},
      {de:'die Angst',ru:'страх',ex:'Angst haben.',cat:'general'},
      {de:'die Freude',ru:'радость',ex:'Freude empfinden.',cat:'general'},
      {de:'die Trauer',ru:'горе',ex:'Trauer tragen.',cat:'general'},
      {de:'die Liebe',ru:'любовь',ex:'Liebe fühlen.',cat:'general'},
      {de:'der Hass',ru:'ненависть',ex:'Hass empfinden.',cat:'general'},
      {de:'die Ruhe',ru:'покой',ex:'Ruhe finden.',cat:'general'},
      {de:'die Eile',ru:'спешка',ex:'In Eile sein.',cat:'general'},
      {de:'die Geduld',ru:'терпение',ex:'Geduld haben.',cat:'general'},
      {de:'die Ungeduld',ru:'нетерпение',ex:'Ungeduld zeigen.',cat:'general'},
      {de:'die Ruhe',ru:'тишина',ex:'Ruhe bewahren.',cat:'general'},
      {de:'der Lärm',ru:'шум',ex:'Lärm machen.',cat:'general'},
      {de:'die Ordnung',ru:'порядок',ex:'Ordnung halten.',cat:'general'},
      {de:'das Chaos',ru:'хаос',ex:'Chaos stiften.',cat:'general'},
      {de:'die Regel',ru:'правило',ex:'Regeln befolgen.',cat:'general'},
      {de:'die Ausnahme',ru:'исключение',ex:'Eine Ausnahme machen.',cat:'general'},
      {de:'die Norm',ru:'норма',ex:'Das ist die Norm.',cat:'general'},
      {de:'die Abweichung',ru:'отклонение',ex:'Eine Abweichung feststellen.',cat:'general'},
      {de:'die Tradition',ru:'традиция',ex:'Traditionen pflegen.',cat:'general'},
      {de:'die Moderne',ru:'современность',ex:'Die Moderne umarmen.',cat:'general'},
      {de:'die Kultur',ru:'культура',ex:'Kultur erleben.',cat:'general'},
      {de:'die Kunst',ru:'искусство',ex:'Kunst schätzen.',cat:'general'},
      {de:'die Musik',ru:'музыка',ex:'Musik hören.',cat:'general'},
      {de:'die Literatur',ru:'литература',ex:'Literatur lesen.',cat:'general'},
      {de:'die Wissenschaft',ru:'наука',ex:'Wissenschaft betreiben.',cat:'general'},
      {de:'die Technik',ru:'техника',ex:'Technik anwenden.',cat:'general'},
      {de:'die Wirtschaft',ru:'экономика',ex:'Wirtschaft studieren.',cat:'general'},
      {de:'die Politik',ru:'политика',ex:'Politik machen.',cat:'general'},
      {de:'die Gesellschaft',ru:'общество',ex:'Gesellschaft formen.',cat:'general'},
      {de:'die Familie',ru:'семья',ex:'Familie unterstützen.',cat:'general'},
      {de:'die Freundschaft',ru:'дружба',ex:'Freundschaft pflegen.',cat:'general'},
      {de:'die Beziehung',ru:'отношения',ex:'Beziehungen aufbauen.',cat:'general'},
      {de:'die Ehe',ru:'брак',ex:'Ehe schließen.',cat:'general'},
      {de:'die Scheidung',ru:'развод',ex:'Scheidung einreichen.',cat:'general'},
      {de:'die Geburt',ru:'рождение',ex:'Geburt feiern.',cat:'general'},
      {de:'der Tod',ru:'смерть',ex:'Tod akzeptieren.',cat:'general'},
      {de:'das Leben',ru:'жизнь',ex:'Leben genießen.',cat:'general'},
    ],
    quiz:[
      {q:'die Möglichkeit',opts:['невозможность','возможность','реальность','ситуация'],a:1},
      {q:'der Erfolg',opts:['неудача','успех','начало','конец'],a:1},
    ]
  },
];

const SPEC_VOCAB = {
  it: [
    {de:'das Netzwerk',ru:'сеть',ex:'Das Netzwerk ist ausgefallen.',cat:'IT'},
    {de:'der Server',ru:'сервер',ex:'Der Server wird neu gestartet.',cat:'IT'},
    {de:'die Firewall',ru:'брандмауэр',ex:'Die Firewall blockiert die Verbindung.',cat:'IT'},
    {de:'die Sicherung',ru:'резервная копия / бэкап',ex:'Bitte erstellen Sie eine Sicherung.',cat:'IT'},
    {de:'das Betriebssystem',ru:'операционная система',ex:'Das Betriebssystem muss aktualisiert werden.',cat:'IT'},
    {de:'der Benutzer',ru:'пользователь',ex:'Der Benutzer hat kein Kennwort.',cat:'IT'},
    {de:'das Kennwort',ru:'пароль',ex:'Ihr Kennwort ist abgelaufen.',cat:'IT'},
    {de:'die Störung',ru:'сбой / неполадка',ex:'Es gibt eine Störung im System.',cat:'IT'},
    {de:'der Zugriff',ru:'доступ',ex:'Der Zugriff wurde verweigert.',cat:'IT'},
    {de:'die Verschlüsselung',ru:'шифрование',ex:'Wir nutzen starke Verschlüsselung.',cat:'IT'},
    {de:'das Update',ru:'обновление',ex:'Das Update wird installiert.',cat:'IT'},
    {de:'die Verbindung',ru:'соединение / подключение',ex:'Die Verbindung ist unterbrochen.',cat:'IT'},
    {de:'die Datenbank',ru:'база данных',ex:'Die Datenbank ist beschädigt.',cat:'IT'},
    {de:'der Code',ru:'код',ex:'Der Code muss überprüft werden.',cat:'IT'},
    {de:'der Fehler',ru:'ошибка',ex:'Es gibt einen Fehler im Programm.',cat:'IT'},
    {de:'die Hardware',ru:'аппаратное обеспечение',ex:'Die Hardware ist veraltet.',cat:'IT'},
    {de:'die Software',ru:'программное обеспечение',ex:'Die Software läuft langsam.',cat:'IT'},
    {de:'der Support',ru:'поддержка',ex:'Kontaktieren Sie den Support.',cat:'IT'},
    {de:'die Cloud',ru:'облако',ex:'Daten in der Cloud speichern.',cat:'IT'},
    {de:'das Backup',ru:'резервная копия',ex:'Machen Sie ein Backup.',cat:'IT'},
  ],
  med: [
    {de:'der Patient',ru:'пациент',ex:'Der Patient hat Fieber.',cat:'Медицина'},
    {de:'die Diagnose',ru:'диагноз',ex:'Die Diagnose lautet: Grippe.',cat:'Медицина'},
    {de:'das Rezept',ru:'рецепт',ex:'Ich brauche ein Rezept.',cat:'Медицина'},
    {de:'der Blutdruck',ru:'кровяное давление',ex:'Ihr Blutdruck ist zu hoch.',cat:'Медицина'},
    {de:'die Tablette',ru:'таблетка',ex:'Nehmen Sie diese Tablette.',cat:'Медицина'},
    {de:'die Untersuchung',ru:'обследование',ex:'Eine Untersuchung ist notwendig.',cat:'Медицина'},
    {de:'das Krankenhaus',ru:'больница',ex:'Er ist im Krankenhaus.',cat:'Медицина'},
    {de:'der Arzt',ru:'врач',ex:'Der Arzt untersucht mich.',cat:'Медицина'},
    {de:'die Krankenschwester',ru:'медсестра',ex:'Die Krankenschwester hilft.',cat:'Медицина'},
    {de:'die Operation',ru:'операция',ex:'Die Operation war erfolgreich.',cat:'Медицина'},
    {de:'die Therapie',ru:'терапия',ex:'Die Therapie beginnt morgen.',cat:'Медицина'},
    {de:'das Symptom',ru:'симптом',ex:'Welche Symptome haben Sie?',cat:'Медицина'},
    {de:'die Behandlung',ru:'лечение',ex:'Die Behandlung dauert lange.',cat:'Медицина'},
    {de:'die Impfung',ru:'прививка',ex:'Die Impfung schützt.',cat:'Медицина'},
    {de:'der Notfall',ru:'экстренный случай',ex:'Das ist ein Notfall.',cat:'Медицина'},
  ],
  law: [
    {de:'der Vertrag',ru:'договор',ex:'Der Vertrag ist ungültig.',cat:'Право'},
    {de:'das Gericht',ru:'суд',ex:'Der Fall geht vor Gericht.',cat:'Право'},
    {de:'die Klage',ru:'иск',ex:'Eine Klage wurde eingereicht.',cat:'Право'},
    {de:'der Anwalt',ru:'адвокат',ex:'Mein Anwalt prüft den Vertrag.',cat:'Право'},
    {de:'das Gesetz',ru:'закон',ex:'Das Gesetz ist eindeutig.',cat:'Право'},
    {de:'die Haftung',ru:'ответственность',ex:'Die Haftung liegt beim Arbeitgeber.',cat:'Право'},
    {de:'der Richter',ru:'судья',ex:'Der Richter entscheidet.',cat:'Право'},
    {de:'die Strafe',ru:'наказание',ex:'Die Strafe ist hoch.',cat:'Право'},
    {de:'das Urteil',ru:'приговор',ex:'Das Urteil ist gefallen.',cat:'Право'},
    {de:'die Rechte',ru:'права',ex:'Ihre Rechte sind geschützt.',cat:'Право'},
    {de:'die Pflicht',ru:'обязанность',ex:'Das ist Ihre Pflicht.',cat:'Право'},
    {de:'der Zeuge',ru:'свидетель',ex:'Der Zeuge sagt aus.',cat:'Право'},
    {de:'der Beweis',ru:'доказательство',ex:'Es gibt keine Beweise.',cat:'Право'},
    {de:'die Verhandlung',ru:'переговоры / слушание',ex:'Die Verhandlung beginnt.',cat:'Право'},
  ],
  fin: [
    {de:'die Rechnung',ru:'счёт / счёт-фактура',ex:'Bitte bezahlen Sie die Rechnung.',cat:'Финансы'},
    {de:'der Kredit',ru:'кредит',ex:'Ich beantrage einen Kredit.',cat:'Финансы'},
    {de:'die Investition',ru:'инвестиция',ex:'Eine riskante Investition.',cat:'Финансы'},
    {de:'der Umsatz',ru:'оборот / выручка',ex:'Der Umsatz ist gestiegen.',cat:'Финансы'},
    {de:'das Budget',ru:'бюджет',ex:'Das Budget wurde überschritten.',cat:'Финансы'},
    {de:'die Steuer',ru:'налог',ex:'Die Steuer muss bezahlt werden.',cat:'Финансы'},
    {de:'die Bank',ru:'банк',ex:'Ich gehe zur Bank.',cat:'Финансы'},
    {de:'das Konto',ru:'счёт',ex:'Mein Konto ist leer.',cat:'Финансы'},
    {de:'die Zinsen',ru:'проценты',ex:'Die Zinsen sind hoch.',cat:'Финансы'},
    {de:'die Versicherung',ru:'страховка',ex:'Die Versicherung deckt alles.',cat:'Финансы'},
    {de:'die Dividende',ru:'дивиденд',ex:'Die Dividende wird ausgezahlt.',cat:'Финансы'},
    {de:'der Gewinn',ru:'прибыль',ex:'Der Gewinn ist hoch.',cat:'Финансы'},
    {de:'der Verlust',ru:'убыток',ex:'Wir haben Verluste.',cat:'Финансы'},
  ],
  eng: [
    {de:'die Maschine',ru:'машина / станок',ex:'Die Maschine ist defekt.',cat:'Инженерия'},
    {de:'der Antrieb',ru:'привод / двигатель',ex:'Der Antrieb funktioniert nicht.',cat:'Инженерия'},
    {de:'die Wartung',ru:'техническое обслуживание',ex:'Wartung ist fällig.',cat:'Инженерия'},
    {de:'der Werkstoff',ru:'материал',ex:'Der richtige Werkstoff ist wichtig.',cat:'Инженерия'},
    {de:'die Toleranz',ru:'допуск',ex:'Die Toleranz beträgt 0,1 mm.',cat:'Инженерия'},
    {de:'der Plan',ru:'план / чертёж',ex:'Der Plan ist fertig.',cat:'Инженерия'},
    {de:'die Konstruktion',ru:'конструкция',ex:'Die Konstruktion ist stabil.',cat:'Инженерия'},
    {de:'der Test',ru:'тест',ex:'Der Test war erfolgreich.',cat:'Инженерия'},
    {de:'die Sicherheit',ru:'безопасность',ex:'Sicherheit geht vor.',cat:'Инженерия'},
    {de:'die Energie',ru:'энергия',ex:'Erneuerbare Energie.',cat:'Инженерия'},
    {de:'der Prozess',ru:'процесс',ex:'Der Prozess läuft.',cat:'Инженерия'},
  ],
  biz: [
    {de:'die Verhandlung',ru:'переговоры',ex:'Die Verhandlung war erfolgreich.',cat:'Бизнес'},
    {de:'das Angebot',ru:'предложение / оффер',ex:'Wir schicken ein Angebot.',cat:'Бизнес'},
    {de:'der Kunde',ru:'клиент',ex:'Der Kunde ist zufrieden.',cat:'Бизнес'},
    {de:'die Präsentation',ru:'презентация',ex:'Die Präsentation beginnt um 10 Uhr.',cat:'Бизнес'},
    {de:'der Gewinn',ru:'прибыль',ex:'Der Gewinn ist gestiegen.',cat:'Бизнес'},
    {de:'die Besprechung',ru:'совещание',ex:'Die Besprechung dauert eine Stunde.',cat:'Бизнес'},
    {de:'der Markt',ru:'рынок',ex:'Der Markt ist groß.',cat:'Бизнес'},
    {de:'die Strategie',ru:'стратегия',ex:'Eine neue Strategie.',cat:'Бизнес'},
    {de:'der Vertrag',ru:'контракт',ex:'Der Vertrag ist unterschrieben.',cat:'Бизнес'},
    {de:'die Partnerschaft',ru:'партнёрство',ex:'Eine Partnerschaft eingehen.',cat:'Бизнес'},
    {de:'das Ziel',ru:'цель',ex:'Das Ziel erreichen.',cat:'Бизнес'},
    {de:'der Erfolg',ru:'успех',ex:'Das ist ein Erfolg.',cat:'Бизнес'},
  ],
};

const SPEC_LESSONS = {
  it: [
    { id:'it1', title:'IT: Базовая терминология', de:'IT-Grundbegriffe', color:'c-blue', type:'IT A1',
      words: SPEC_VOCAB.it.slice(0,6),
      quiz:[
        {q:'das Netzwerk',opts:['сервер','сеть','пароль','доступ'],a:1},
        {q:'das Kennwort',opts:['доступ','шифрование','пароль','обновление'],a:2},
      ]
    },
    { id:'it2', title:'IT: Безопасность и доступ', de:'Sicherheit & Zugriff', color:'c-purple', type:'IT A2',
      words: SPEC_VOCAB.it.slice(6),
      quiz:[
        {q:'die Verschlüsselung',opts:['шифрование','брандмауэр','бэкап','доступ'],a:0},
        {q:'der Zugriff',opts:['пользователь','доступ','обновление','соединение'],a:1},
      ]
    },
  ],
  med: [
    { id:'med1', title:'Медицина: Базовые термины', de:'Medizinische Grundbegriffe', color:'c-teal', type:'Медицина A1',
      words: SPEC_VOCAB.med,
      quiz:[
        {q:'die Diagnose',opts:['рецепт','диагноз','лекарство','больница'],a:1},
        {q:'das Krankenhaus',opts:['аптека','больница','клиника','кабинет'],a:1},
      ]
    },
  ],
  fin: [
    { id:'fin1', title:'Финансы: Основные понятия', de:'Finanzbegriffe', color:'c-gold', type:'Финансы A1',
      words: SPEC_VOCAB.fin,
      quiz:[
        {q:'die Steuer',opts:['кредит','бюджет','налог','оборот'],a:2},
        {q:'der Umsatz',opts:['прибыль','расход','оборот','налог'],a:2},
      ]
    },
  ],
  biz: [
    { id:'biz1', title:'Бизнес: Деловой немецкий', de:'Geschäftsdeutsch', color:'c-orange', type:'Бизнес A1',
      words: SPEC_VOCAB.biz,
      quiz:[
        {q:'die Verhandlung',opts:['презентация','переговоры','клиент','прибыль'],a:1},
        {q:'der Gewinn',opts:['расход','прибыль','клиент','оффер'],a:1},
      ]
    },
  ],
  law: [
    { id:'law1', title:'Право: Юридические термины', de:'Rechtsbegriffe', color:'c-purple', type:'Право A1',
      words: SPEC_VOCAB.law,
      quiz:[
        {q:'der Vertrag',opts:['суд','иск','договор','закон'],a:2},
        {q:'die Haftung',opts:['адвокат','закон','ответственность','иск'],a:2},
      ]
    },
  ],
  eng: [
    { id:'eng1', title:'Инженерия: Техническая терминология', de:'Technische Begriffe', color:'c-green', type:'Инженерия A1',
      words: SPEC_VOCAB.eng,
      quiz:[
        {q:'die Wartung',opts:['привод','допуск','обслуживание','материал'],a:2},
        {q:'die Toleranz',opts:['инструмент','допуск','скорость','вес'],a:1},
      ]
    },
  ],
};

const PHRASES = [
  {de:'Guten Morgen!',ru:'Доброе утро!',cat:'Приветствие'},
  {de:'Auf Wiedersehen!',ru:'До свидания!',cat:'Прощание'},
  {de:'Danke schön!',ru:'Большое спасибо!',cat:'Вежливость'},
  {de:'Entschuldigung!',ru:'Извините!',cat:'Вежливость'},
  {de:'Ich verstehe nicht.',ru:'Я не понимаю.',cat:'Общение'},
  {de:'Können Sie das wiederholen?',ru:'Можете повторить?',cat:'Общение'},
  {de:'Wie viel kostet das?',ru:'Сколько стоит?',cat:'Магазин'},
  {de:'Wo ist...?',ru:'Где находится...?',cat:'Навигация'},
  {de:'Ich lerne Deutsch.',ru:'Я учу немецкий.',cat:'Учёба'},
  {de:'Noch einmal, bitte.',ru:'Ещё раз, пожалуйста.',cat:'Учёба'},
  {de:'Das ist richtig.',ru:'Это правильно.',cat:'Общение'},
  {de:'Ich brauche Hilfe.',ru:'Мне нужна помощь.',cat:'Общение'},
];
